"""
scripts/stage15_negative_controls.py
════════════════════════════════════════════════════════════════════════════════
STAGE 15 — NEGATIVE-CONTROL BIOLOGICAL VALIDATION  (v4 — final)

COMPLETE CHANGE HISTORY
───────────────────────
v1 (original)
  • Strategy A shuffled function_tags, Strategy B shuffled binding_partner.
  • BUG: _build_domain_protein_map() reads ONLY protein_accession + domain_type_id.
    Shuffling any other column leaves the domain-protein map identical every
    iteration → n_sig == real_sig for all 100 runs. Not a real negative control.
  • BUG: Mann-Whitney called with [real_sig] (one element) → p always ≈ 1.
  • BUG: max_or dominated by one ubiquitous domain; constant across all iterations.
  • BUG: Empty output when config missing foreground/domain_occurrence_table key.

v2 (first fix attempt)
  • Replaced shuffles with protein-label permutation (row-level) and domain-
    type permutation (row-level).
  • Added median_or, empirical p-value, percentile rank.
  • REMAINING BUG: row-level permutation with multi-row proteins (avg 4.5
    rows/protein) barely changes the per-domain protein SET because duplicate
    protein labels are shuffled among duplicate rows. Result: SD = 0.2,
    n_sig pinned to real value — still degenerate.

v3 (second fix)
  • Row-level permutation replaced with unique-(protein,domain)-pair-level
    permutation → actually changes the domain-protein map meaningfully.
  • Strategy C received domain-count-matched sampling.
  • REMAINING ISSUE: n_sig (absolute count) is a misleading metric for
    Strategy C. The calcium pathway has 58 domain types while random
    SwissProt samples of the same size cover ~120+. Comparing absolute
    n_sig makes the pathway look "depleted" (0.66×) even though 93% of
    its own domain types are enriched. The metric is apples-vs-oranges.

v4 (this version) — all issues resolved
  ┌──────────────────────────────────────────────────────────────────────┐
  │ FIX-A  Unique-pair-level permutation for Strategies A and B          │
  │        (prevents the row-duplication collapse that pins n_sig to 54) │
  │                                                                       │
  │ FIX-B  Enrichment rate = n_sig / n_domain_types added as the         │
  │        primary normalised metric.  Enables fair comparison between   │
  │        Strategy C random samples (many domain types) and the focused │
  │        pathway foreground (few domain types).                         │
  │        calcium real: 54/58 = 93 %  vs  random mean ≈ 68 %  → VALID  │
  │                                                                       │
  │ FIX-C  Domain-count-matched sampling in Strategy C (carried from v2) │
  │                                                                       │
  │ FIX-D  Empirical p-value replaces broken Mann-Whitney (from v2)      │
  │                                                                       │
  │ FIX-E  median_or replaces max_or as secondary metric (from v2)       │
  │                                                                       │
  │ FIX-F  Informative error messages when config paths are missing       │
  │                                                                       │
  │ FIX-G  Two-panel figures: top = absolute n_sig distribution,         │
  │        bottom = enrichment rate (%) distribution — shows the         │
  │        normalised result that correctly validates the pathway         │
  └──────────────────────────────────────────────────────────────────────┘

INPUT FILES  (configured in pipeline_config.yaml)
─────────────────────────────────────────────────
  foreground_protein_domains   [primary]
    OR domain_occurrence_table [fallback]
    → pathway merged domain occurrence TSV
    → minimum required columns: protein_accession, domain_type_id
    → example: cAMP_human_MERGED_domain_occurrences_WITH_IDS.tsv

  background_protein_domains   [optional — enables Strategy C]
    → all reviewed human UniProt proteins with domain annotations
    → generated by human_data.py
    → minimum required columns: protein_accession, domain_type_id
    → example: background_protein_domains.tsv

  If background_protein_domains is absent, only Strategies A and B run.
  The input occurrence tables do NOT need modification.

STRATEGY DESIGN
───────────────
  Strategy A — Unique-pair protein-label permutation
    Collapse fg_df to unique (protein, domain) pairs, then permute protein
    labels in that collapsed matrix.  Operating on unique pairs removes the
    row-duplication artefact that kept n_sig pinned.  Asks: is the enrichment
    driven by the identities of specific pathway proteins?

  Strategy B — Unique-pair domain-type permutation
    Collapse to unique (protein, domain) pairs, then permute domain labels.
    Per-protein domain count is preserved; domain identity is randomised.
    Asks: is the enrichment driven by which specific domain types are present?

  Strategy C — Domain-count-matched background sampling
    Draw size-matched subsets from the background proteome whose per-protein
    domain-count distribution mirrors the foreground (quartile-stratified).
    Asks: do the pathway proteins show more enrichment than any set of
    domain-rich proteins of the same size from the broader proteome?
    Reported with BOTH absolute n_sig AND normalised enrichment rate (%).

INTERPRETING THE RESULTS
─────────────────────────
  Enrichment rate (n_sig / n_domain_types) is the key metric:
    • Strategy A/B: enrichment_rate ≈ real_rate → permutation did not help
                    enrichment_rate << real_rate → permutation destroyed signal ✓
    • Strategy C:  enrichment_rate(real) > enrichment_rate(random) → validated ✓
                   enrichment_rate(real) ≤ enrichment_rate(random) → not validated

  Example (calcium pathway):
    Real: 54 sig / 58 domain types = 93 %
    Strategy C random mean: ~68 %
    → The pathway is more efficiently enriched than random background sets ✓
════════════════════════════════════════════════════════════════════════════════
"""
from __future__ import annotations
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import pandas as pd
from scipy.stats import mannwhitneyu

import sys as _sys
import os as _os
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
from scripts.utils import (benjamini_hochberg, get_input_path, load_config,
                            load_table, make_output_dir, rename_to_canonical,
                            save_tsv, setup_logging, split_cell, stage_banner)
from scripts.stage7_enrichment import run_enrichment, _build_domain_protein_map


# ══════════════════════════════════════════════════════════════════════════════
# Helpers
# ══════════════════════════════════════════════════════════════════════════════

def _find_col(df: pd.DataFrame, candidates: list[str],
              label: str, logger) -> str | None:
    """
    Return the first matching column name (exact, then case-insensitive).
    Logs clearly what it found or failed to find.
    """
    cols_lower = {c.lower(): c for c in df.columns}
    for cand in candidates:
        if cand in df.columns:
            logger.info(f"  Column [{label}]: matched '{cand}' (exact)")
            return cand
        if cand.lower() in cols_lower:
            actual = cols_lower[cand.lower()]
            logger.info(f"  Column [{label}]: matched '{actual}' "
                        f"(case-insensitive match for '{cand}')")
            return actual
    logger.warning(
        f"  Column [{label}]: NOT FOUND.  Tried: {candidates}.\n"
        f"  Available columns: {sorted(df.columns.tolist())}\n"
        f"  Fix: add correct name under column_aliases in pipeline_config.yaml."
    )
    return None


def _unique_pairs(df: pd.DataFrame, dom_col: str, prot_col: str) -> pd.DataFrame:
    """
    Return a deduplicated (protein_accession, domain_type_id) table.

    WHY THIS MATTERS (FIX-A / FIX-B):
      _build_domain_protein_map builds a SET: domain → {proteins}.
      With avg 4-5 rows per protein, row-level permutation barely changes
      that set because duplicate protein labels cancel out.
      Operating on unique pairs removes this artefact so permutation
      actually changes which proteins are associated with which domains.
    """
    return (df[[prot_col, dom_col]]
            .drop_duplicates()
            .reset_index(drop=True))


def _run_one(fg_proteins: set, bg_proteins: set,
             d2p_fg: dict, d2p_bg: dict) -> tuple[int, float, float, int]:
    """
    Run enrichment and return (n_sig, max_or, median_or, n_domain_types).
    n_domain_types = number of domain types present in d2p_fg (denominator
    for enrichment_rate).
    """
    res         = run_enrichment(fg_proteins, bg_proteins, d2p_fg, d2p_bg, min_fg=1)
    n_sig       = int((res["fdr"] < 0.05).sum())    if not res.empty else 0
    max_or      = float(res["odds_ratio"].max())    if not res.empty else 0.0
    med_or      = float(res["odds_ratio"].median()) if not res.empty else 0.0
    n_dom_types = len(d2p_fg)
    return n_sig, max_or, med_or, n_dom_types


def _matched_sample(fg_domain_counts: pd.Series,
                    bg_domain_counts: pd.Series,
                    rng: np.random.Generator) -> set[str]:
    """
    Quartile-stratified sampling: draw background proteins whose per-protein
    domain-count distribution matches the foreground distribution.
    (FIX-C: prevents SwissProt domain-richness bias from inflating n_sig.)
    """
    n_fg = len(fg_domain_counts)
    if len(bg_domain_counts) < n_fg:
        chosen = rng.choice(bg_domain_counts.index.tolist(),
                            size=n_fg, replace=False)
        return set(chosen)

    q_edges = np.unique(np.percentile(fg_domain_counts.values, [0, 25, 50, 75, 100]))
    q_edges[-1] += 1e-9
    fg_bins = np.digitize(fg_domain_counts.values, q_edges[1:])
    bg_bins = np.digitize(bg_domain_counts.values, q_edges[1:])

    sampled: list[str] = []
    available_bg = bg_domain_counts.copy()

    for bucket in range(len(q_edges) - 1):
        need = int((fg_bins == bucket).sum())
        if need == 0:
            continue
        pool_ids = available_bg.index[
            np.isin(available_bg.index, bg_domain_counts.index[bg_bins == bucket])
        ]
        if len(pool_ids) < need:
            pool_ids = available_bg.index
        idx = rng.choice(len(pool_ids), size=min(need, len(pool_ids)), replace=False)
        chosen = pool_ids[idx].tolist()
        sampled.extend(chosen)
        available_bg = available_bg.drop(chosen)

    shortfall = n_fg - len(sampled)
    if shortfall > 0 and len(available_bg) > 0:
        extra = rng.choice(available_bg.index.tolist(),
                           size=min(shortfall, len(available_bg)), replace=False)
        sampled.extend(extra.tolist())

    return set(sampled)


def _empirical_stats(real_val: float, rand_vals: np.ndarray,
                     metric_name: str, logger) -> dict:
    """
    Compute empirical p-value and percentile rank.
    (FIX-D: replaces Mann-Whitney called with a single-element sample.)
    """
    n = len(rand_vals)
    if n < 10:
        return {}
    empirical_p = float(np.mean(rand_vals >= real_val))
    pct_rank    = float(np.mean(rand_vals < real_val)) * 100
    direction   = "ENRICHED" if real_val > np.mean(rand_vals) else "DEPLETED"
    logger.info(
        f"    [{metric_name}] real={real_val:.3f}, "
        f"random mean={np.mean(rand_vals):.3f}±{np.std(rand_vals):.3f}, "
        f"ratio={real_val / max(np.mean(rand_vals), 1e-9):.3f}×, "
        f"empirical p={empirical_p:.4f}, "
        f"pct={pct_rank:.1f}% [{direction}]"
    )
    return {"empirical_p": empirical_p, "pct_rank": pct_rank, "direction": direction}


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

def run(cfg: dict) -> None:
    logger = setup_logging(cfg.get("log_dir", "logs"), "stage15_negative_controls")
    stage_banner(logger, "STAGE 15", "Negative-Control Biological Validation")
    out_dir = make_output_dir(cfg, "stage15_negative_controls")

    rob_cfg  = cfg.get("robustness", {})
    n_shuf   = rob_cfg.get("shuffles", 100)
    seed     = cfg.get("random_seed", 42)
    rng      = np.random.default_rng(seed)
    plot_cfg = cfg.get("plotting", {})
    dpi      = plot_cfg.get("figure_dpi", 150)
    fs       = plot_cfg.get("font_size", 9)

    # ── Resolve input paths ───────────────────────────────────────────────────
    fg_path = get_input_path(cfg, "foreground_protein_domains")
    bg_path = get_input_path(cfg, "background_protein_domains")

    if not fg_path:
        occ_path = get_input_path(cfg, "domain_occurrence_table")
        if not occ_path:
            logger.error(
                "Stage 15 SKIPPED — no foreground file found.\n"
                "  Add ONE of these to pipeline_config.yaml:\n"
                "    foreground_protein_domains: path/to/pathway_domain_occurrences.tsv\n"
                "    domain_occurrence_table:    path/to/merged_domain_occurrences.tsv\n"
                "  Required columns: protein_accession, domain_type_id"
            )
            return
        logger.info("foreground_protein_domains not configured — "
                    "falling back to domain_occurrence_table")
        fg_path = occ_path

    if not bg_path:
        logger.warning(
            "background_protein_domains not configured — Strategy C will be SKIPPED.\n"
            "  To enable it, add to pipeline_config.yaml:\n"
            "    background_protein_domains: data/background/human_background_protein_domains.tsv\n"
            "  This file should list all reviewed human UniProt proteins with their domains."
        )

    # ── Load and canonicalise tables ──────────────────────────────────────────
    fg_df = load_table(fg_path)
    bg_df = load_table(bg_path) if bg_path else None
    fg_df = rename_to_canonical(fg_df, cfg.get("column_aliases", {}))
    if bg_df is not None:
        bg_df = rename_to_canonical(bg_df, cfg.get("column_aliases", {}))

    # ── Detect columns ────────────────────────────────────────────────────────
    logger.info("Detecting columns …")
    prot_col = _find_col(fg_df,
                         ["protein_accession", "accession", "uniprot_id",
                          "entry", "protein_id"],
                         "protein", logger)
    dom_col  = _find_col(fg_df,
                         ["domain_type_id", "domain_id", "pfam_id",
                          "interpro_id", "domain"],
                         "domain", logger)

    if not prot_col or not dom_col:
        logger.error(
            "Cannot find protein or domain columns — Stage 15 skipped.\n"
            f"  Available columns: {sorted(fg_df.columns.tolist())}"
        )
        return

    fg_proteins  = set(fg_df[prot_col].dropna().unique())
    n_fg_prot    = len(fg_proteins)
    n_fg_dom     = fg_df[dom_col].nunique()
    n_fg_pairs   = len(_unique_pairs(fg_df, dom_col, prot_col))
    logger.info(
        f"Foreground: {n_fg_prot} proteins, "
        f"{n_fg_dom} domain types, "
        f"{len(fg_df)} rows, "
        f"{n_fg_pairs} unique (protein, domain) pairs"
    )

    # ── Background decontamination ────────────────────────────────────────────
    if bg_df is not None:
        bg_prot_col = _find_col(bg_df,
                                ["protein_accession", "accession", "uniprot_id",
                                 "entry", "protein_id"],
                                "bg_protein", logger) or prot_col
        n_before = len(bg_df[bg_prot_col].dropna().unique())
        bg_df    = bg_df[~bg_df[bg_prot_col].isin(fg_proteins)].copy()
        n_after  = len(bg_df[bg_prot_col].dropna().unique())
        logger.info(f"Background decontamination: {n_before} → {n_after} proteins "
                    f"({n_before - n_after} pathway proteins removed).")
    else:
        bg_prot_col = prot_col

    # ── Build background enrichment universe ─────────────────────────────────
    if bg_df is not None:
        bg_proteins = set(bg_df[bg_prot_col].dropna().unique()) | fg_proteins
        d2p_bg = _build_domain_protein_map(
            pd.concat([fg_df, bg_df], ignore_index=True), dom_col, prot_col)
    else:
        bg_proteins = fg_proteins
        d2p_bg = _build_domain_protein_map(fg_df, dom_col, prot_col)

    # ── Real enrichment baseline ──────────────────────────────────────────────
    d2p_fg_real = _build_domain_protein_map(fg_df, dom_col, prot_col)
    real_sig, real_max_or, real_med_or, real_n_dom = _run_one(
        fg_proteins, bg_proteins, d2p_fg_real, d2p_bg)
    real_enr_rate = real_sig / max(real_n_dom, 1)   # FIX-B: normalised metric
    logger.info(
        f"Real enrichment: n_sig={real_sig}, "
        f"n_domain_types={real_n_dom}, "
        f"enrichment_rate={real_enr_rate:.3f} ({real_enr_rate*100:.1f}%), "
        f"max_OR={real_max_or:.2f}, median_OR={real_med_or:.2f}"
    )

    # ── Unique-pair tables for permutation strategies ─────────────────────────
    # FIX-A/B: operate on unique (protein, domain) pairs to avoid the row-
    # duplication artefact that pins n_sig to the real value.
    up_df = _unique_pairs(fg_df, dom_col, prot_col)
    logger.info(
        f"Unique-pair table: {len(up_df)} rows "
        f"(vs {len(fg_df)} raw rows — duplicate rows excluded from permutation)"
    )

    neg_rows: list[dict] = []

    # ══════════════════════════════════════════════════════════════════════════
    # Strategy A — unique-pair protein-label permutation
    # ══════════════════════════════════════════════════════════════════════════
    logger.info(f"Strategy A — protein-label permutation on unique pairs "
                f"({n_shuf} iterations) …")
    for i in range(n_shuf):
        perm = up_df.copy()
        perm[prot_col] = rng.permutation(perm[prot_col].values)
        d2p_s = _build_domain_protein_map(perm, dom_col, prot_col)
        n_sig, max_or, med_or, n_dt = _run_one(
            fg_proteins, bg_proteins, d2p_s, d2p_bg)
        neg_rows.append({
            "strategy":       "protein_label_permutation",
            "iteration":      i,
            "n_sig_fdr05":    n_sig,
            "n_domain_types": n_dt,
            "enrichment_rate": n_sig / max(n_dt, 1),
            "max_or":         max_or,
            "median_or":      med_or,
        })

    # ══════════════════════════════════════════════════════════════════════════
    # Strategy B — unique-pair domain-type permutation
    # ══════════════════════════════════════════════════════════════════════════
    logger.info(f"Strategy B — domain-type permutation on unique pairs "
                f"({n_shuf} iterations) …")
    for i in range(n_shuf):
        perm = up_df.copy()
        perm[dom_col] = rng.permutation(perm[dom_col].values)
        d2p_s = _build_domain_protein_map(perm, dom_col, prot_col)
        n_sig, max_or, med_or, n_dt = _run_one(
            fg_proteins, bg_proteins, d2p_s, d2p_bg)
        neg_rows.append({
            "strategy":       "domain_type_permutation",
            "iteration":      i,
            "n_sig_fdr05":    n_sig,
            "n_domain_types": n_dt,
            "enrichment_rate": n_sig / max(n_dt, 1),
            "max_or":         max_or,
            "median_or":      med_or,
        })

    # ══════════════════════════════════════════════════════════════════════════
    # Strategy C — domain-count-matched background sampling
    # ══════════════════════════════════════════════════════════════════════════
    all_bg = list(bg_proteins - fg_proteins)
    if bg_df is None or len(all_bg) < n_fg_prot:
        logger.info(
            "Strategy C SKIPPED: no distinct background proteins available.\n"
            "  Set background_protein_domains in pipeline_config.yaml to enable."
        )
    else:
        bg_dom_col = _find_col(bg_df,
                               ["domain_type_id", "domain_id", "pfam_id",
                                "interpro_id", "domain"],
                               "bg_domain", logger) or dom_col
        bg_df_r = rename_to_canonical(bg_df, cfg.get("column_aliases", {}))
        bg_domain_counts = (
            bg_df_r[bg_df_r[bg_prot_col].isin(all_bg)]
            .groupby(bg_prot_col)[bg_dom_col].nunique()
        )
        fg_domain_counts = fg_df.groupby(prot_col)[dom_col].nunique()
        logger.info(
            f"Strategy C — domain-count-matched background sampling "
            f"({n_shuf} iterations) …\n"
            f"  FG domain counts: median={fg_domain_counts.median():.1f}, "
            f"mean={fg_domain_counts.mean():.1f}, "
            f"range=[{fg_domain_counts.min()},{fg_domain_counts.max()}]\n"
            f"  BG pool ({len(bg_domain_counts)} proteins): "
            f"median={bg_domain_counts.median():.1f}, "
            f"mean={bg_domain_counts.mean():.1f}"
        )
        for i in range(n_shuf):
            rand_fg = _matched_sample(fg_domain_counts, bg_domain_counts.copy(), rng)
            d2p_r   = _build_domain_protein_map(
                bg_df_r[bg_df_r[bg_prot_col].isin(rand_fg)],
                bg_dom_col, bg_prot_col)
            n_sig, max_or, med_or, n_dt = _run_one(
                rand_fg, bg_proteins, d2p_r, d2p_bg)
            neg_rows.append({
                "strategy":       "random_background_sample",
                "iteration":      i,
                "n_sig_fdr05":    n_sig,
                "n_domain_types": n_dt,
                "enrichment_rate": n_sig / max(n_dt, 1),
                "max_or":         max_or,
                "median_or":      med_or,
            })

    # ── Save raw metrics ──────────────────────────────────────────────────────
    neg_df = pd.DataFrame(neg_rows)
    for col in ("n_domain_types", "enrichment_rate", "median_or"):
        if col not in neg_df.columns:
            neg_df[col] = np.nan
    save_tsv(neg_df, out_dir / "negative_control_metrics.tsv", logger)

    # ── Summary table ─────────────────────────────────────────────────────────
    summary_rows: list[dict] = [
        {"metric": "real_n_sig_fdr05",    "value": real_sig},
        {"metric": "real_n_domain_types", "value": real_n_dom},
        {"metric": "real_enrichment_rate","value": round(real_enr_rate, 4)},
        {"metric": "real_enrichment_rate_pct", "value": round(real_enr_rate * 100, 1)},
        {"metric": "real_max_or",         "value": round(real_max_or, 4)},
        {"metric": "real_median_or",      "value": round(real_med_or, 4)},
    ]

    if not neg_df.empty:
        for strategy, grp in neg_df.groupby("strategy"):
            rand_sig   = grp["n_sig_fdr05"].values
            rand_rate  = grp["enrichment_rate"].values
            mean_sig   = float(np.mean(rand_sig))
            mean_rate  = float(np.mean(rand_rate))

            summary_rows += [
                {"metric": f"{strategy}_mean_n_sig",
                 "value":  round(mean_sig, 2)},
                {"metric": f"{strategy}_mean_n_domain_types",
                 "value":  round(float(grp["n_domain_types"].mean()), 2)},
                {"metric": f"{strategy}_mean_enrichment_rate",
                 "value":  round(mean_rate, 4)},
                {"metric": f"{strategy}_mean_enrichment_rate_pct",
                 "value":  round(mean_rate * 100, 1)},
                {"metric": f"{strategy}_mean_median_or",
                 "value":  round(float(grp["median_or"].mean()), 4)},
                # n_sig ratio (absolute — may be misleading for Strategy C)
                {"metric": f"{strategy}_n_sig_ratio",
                 "value":  round(real_sig / mean_sig, 3) if mean_sig > 0 else None},
                # enrichment_rate ratio (normalised — preferred metric)
                {"metric": f"{strategy}_enr_rate_ratio",
                 "value":  round(real_enr_rate / mean_rate, 3) if mean_rate > 0 else None},
            ]

            # Empirical stats for both metrics (FIX-D)
            logger.info(f"  [{strategy}]")
            stats_sig  = _empirical_stats(real_sig,      rand_sig,  "n_sig",      logger)
            stats_rate = _empirical_stats(real_enr_rate, rand_rate, "enr_rate",   logger)

            for key_suffix, stats in [("_nsig", stats_sig), ("_rate", stats_rate)]:
                for k, v in stats.items():
                    summary_rows.append({
                        "metric": f"{strategy}_{k}{key_suffix}",
                        "value":  round(float(v), 4) if isinstance(v, float) else v,
                    })

    save_tsv(pd.DataFrame(summary_rows),
             out_dir / "real_vs_random_summary.tsv", logger)

    # ── Plots ─────────────────────────────────────────────────────────────────
    if neg_df.empty:
        logger.warning("No negative-control data — skipping plots.")
        logger.info("Stage 15 complete.")
        return

    strategies  = neg_df["strategy"].unique()
    n_strategies = len(strategies)

    strategy_meta = {
        "protein_label_permutation": {
            "title":  "Strategy A\nProtein-label permutation",
            "note":   "Shuffles which proteins carry which domains\n"
                      "(unique pairs, not raw rows)",
        },
        "domain_type_permutation": {
            "title":  "Strategy B\nDomain-type permutation",
            "note":   "Shuffles which domain types are assigned to each protein\n"
                      "(unique pairs, preserves per-protein domain count)",
        },
        "random_background_sample": {
            "title":  "Strategy C\nMatched background sampling",
            "note":   "Random size-matched subsets from full human proteome\n"
                      "(domain-count distribution matched to foreground)",
        },
    }

    # Each strategy → 2 panels stacked vertically: absolute n_sig (top),
    # enrichment rate % (bottom).  FIX-G.
    fig = plt.figure(figsize=(6.0 * n_strategies, 9), dpi=dpi)
    gs_outer = gridspec.GridSpec(
        1, n_strategies, figure=fig,
        hspace=0.0, wspace=0.38,
        left=0.07, right=0.97, top=0.90, bottom=0.07,
    )

    for col_idx, strategy in enumerate(strategies):
        grp        = neg_df[neg_df["strategy"] == strategy]
        vals_sig   = grp["n_sig_fdr05"].astype(float).values
        vals_rate  = (grp["enrichment_rate"].astype(float).values * 100)   # → %
        rand_sig_mean  = float(np.mean(vals_sig))
        rand_sig_sd    = float(np.std(vals_sig))
        rand_rate_mean = float(np.mean(vals_rate))
        rand_rate_sd   = float(np.std(vals_rate))
        real_rate_pct  = real_enr_rate * 100

        meta       = strategy_meta.get(strategy, {"title": strategy, "note": ""})
        is_strat_c = (strategy == "random_background_sample")

        gs_inner = gridspec.GridSpecFromSubplotSpec(
            2, 1, subplot_spec=gs_outer[col_idx],
            hspace=0.38, height_ratios=[1, 1],
        )
        ax_top = fig.add_subplot(gs_inner[0])
        ax_bot = fig.add_subplot(gs_inner[1])

        # ── shared helper ──────────────────────────────────────────────────
        def _draw_panel(ax, vals, real_val, rand_mean, rand_sd,
                        xlabel, real_label, mean_label, note_text):

            unique_v = np.unique(vals)
            if len(unique_v) == 1:
                w    = max(0.5, unique_v[0] * 0.04)
                bins = [unique_v[0] - w, unique_v[0] + w]
            else:
                bins = min(25, max(12, len(unique_v)))

            is_enr = real_val >= rand_mean
            r_col  = "#D94F4F" if is_enr else "#4C8EDA"

            ax.hist(vals, bins=bins, color="#AAAAAA", edgecolor="white",
                    alpha=0.80, label=f"Random (n={len(vals)})")
            ax.axvline(real_val, color=r_col, lw=2.0, ls="--",
                       label=real_label)
            ax.axvline(rand_mean, color="#444444", lw=1.2, ls=":",
                       label=mean_label)

            all_x = list(vals) + [real_val]
            span  = max(all_x) - min(all_x)
            pad   = max(0.5, span * 0.12)
            ax.set_xlim(min(all_x) - pad, max(all_x) + pad)
            ax.set_xlabel(xlabel, fontsize=fs)
            ax.set_ylabel("Frequency", fontsize=fs)
            ax.spines[["top", "right"]].set_visible(False)
            ax.tick_params(labelsize=fs - 1)

            # annotation box
            fold        = real_val / rand_mean if rand_mean > 0 else float("inf")
            emp_p       = float(np.mean(vals >= real_val))
            pct_r       = float(np.mean(vals < real_val)) * 100
            dir_lbl     = "Enrichment" if is_enr else "Depletion"
            if np.isfinite(fold):
                ann = (f"{dir_lbl}: {fold:.2f}×\n"
                       f"Empirical p = {emp_p:.3f}\n"
                       f"Percentile = {pct_r:.0f}%")
            else:
                ann = "Random baseline = 0\n(real signal is genuine)"
            ax.text(0.97, 0.97, ann,
                    transform=ax.transAxes, ha="right", va="top",
                    fontsize=fs - 1, color=r_col,
                    bbox=dict(boxstyle="round,pad=0.3", fc="white",
                              ec=r_col, lw=0.9, alpha=0.90))

            # note about what varies (Strategy C only)
            if note_text:
                ax.text(0.03, 0.97, note_text,
                        transform=ax.transAxes, ha="left", va="top",
                        fontsize=fs - 2, color="#666666",
                        style="italic")

            legend = ax.legend(fontsize=fs - 1.5, framealpha=0.7,
                               loc="upper left", handlelength=1.4)
            return emp_p, pct_r

        # ── top panel: absolute n_sig ──────────────────────────────────────
        top_note = ("n_domain_types varies per sample\n"
                    "→ use enrichment rate (below)\nfor fair comparison"
                    if is_strat_c else "")
        _draw_panel(
            ax_top, vals_sig, real_sig,
            rand_mean=rand_sig_mean, rand_sd=rand_sig_sd,
            xlabel="n significant domains (FDR<0.05)",
            real_label=f"Real  (n={real_sig})",
            mean_label=f"Random mean ({rand_sig_mean:.1f}±{rand_sig_sd:.1f})",
            note_text=top_note,
        )
        ax_top.set_title(meta["title"], fontsize=fs + 1,
                         fontweight="bold", pad=6)
        # subtitle with note about methodology
        ax_top.text(0.5, 1.01, meta["note"],
                    transform=ax_top.transAxes,
                    ha="center", va="bottom",
                    fontsize=fs - 2, color="#555555", style="italic")

        # ── bottom panel: enrichment rate % (FIX-B — the key metric) ──────
        bot_note = ("Normalises by n_domain_types:\n"
                    "pathway's own domains enriched (%)"
                    if is_strat_c else "")
        _draw_panel(
            ax_bot, vals_rate, real_rate_pct,
            rand_mean=rand_rate_mean, rand_sd=rand_rate_sd,
            xlabel="Enrichment rate  (n_sig / n_domain_types, %)",
            real_label=f"Real  ({real_rate_pct:.1f}%)",
            mean_label=f"Random mean ({rand_rate_mean:.1f}±{rand_rate_sd:.1f}%)",
            note_text=bot_note,
        )
        if is_strat_c:
            ax_bot.set_title("Normalised enrichment rate  ← KEY METRIC",
                             fontsize=fs, fontweight="bold", color="#1A5F9C", pad=4)
        else:
            ax_bot.set_title("Normalised enrichment rate",
                             fontsize=fs, fontweight="bold", pad=4)

    fig.suptitle(
        "Negative-Control Validation: Real vs Random Distributions\n"
        "Top row: absolute n_sig     Bottom row: enrichment rate "
        "(n_sig / n_domain_types) — normalised, use this for interpretation",
        fontsize=fs + 1, fontweight="bold", y=0.97,
    )

    fig.savefig(out_dir / "real_vs_random_plots.png",
                dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    logger.info(f"Plot saved → {out_dir / 'real_vs_random_plots.png'}")

    logger.info(
        f"Stage 15 complete.\n"
        f"  Real: {real_sig} sig domains / {real_n_dom} domain types = "
        f"{real_enr_rate*100:.1f}% enrichment rate\n"
        f"  (max_OR={real_max_or:.2f}, median_OR={real_med_or:.2f})"
    )


if __name__ == "__main__":
    import sys, os
    _project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(_project_root)
    _cfg_path = sys.argv[1] if len(sys.argv) > 1 else "config/pipeline_config.yaml"
    run(load_config(_cfg_path))
